AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

IneffectiveAccessModifier:
  Enabled: false

Metrics:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
