AllCops:
  TargetRubyVersion: 2.7

Metrics/LineLength:
  Max: 120

IneffectiveAccessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'bin/'
    - 'spec/**/*'
    - 'uploadcare-ruby.gemspec'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
