# currently supported rubies: https://www.ruby-lang.org/en/downloads/branches/

language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7

env:
  UPLOADCARE_PUBLIC_KEY=demopublickey
  UPLOADCARE_SECRET_KEY=demoprivatekey

before_install:
  - gem uninstall bundler
  - gem install bundler --pre
  - bundle update --bundler

jobs:
  include:
    - stage: style checks
      rvm: 2.4
      before_install:
        - gem install rubocop
      script:
        - rubocop

  allow_failures:
    - stage: style checks
    - rvm: 2.6
