# currently supported rubies: https://www.ruby-lang.org/en/downloads/branches/

language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  UPLOADCARE_PUBLIC_KEY=demopublickey
  UPLOADCARE_SECRET_KEY=demoprivatekey

jobs:
  include:
    - stage: style checks
      rvm: 2.7
      before_install:
        - gem install rubocop
      script:
        - rubocop
